# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc443a8c20f3e32dc321241a2887d6ae177db61ad12d4793f8e6391a40f5ff9a9830eb3088bfbeefe8d0dc4c1e8f2d5b67816a65a6ab6e1ddede6fbb6f71e7c

test:
  secret_key_base: 41903e4ac9bb48788248874157412ab9082e2cf68cfbbf71cd2391de301e145141209aa536e4f876054b711d87c5d5ab860dcfc49239a91b4b22faa8ca50f007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
